// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tryout_gigamin1_nugi_mulya_nugraha.Models;

namespace tryout_gigamin1_nugi_mulya_nugraha.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20200227080149_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("tryout_gigamin1_nugi_mulya_nugraha.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Full_name")
                        .HasColumnType("text");

                    b.Property<string>("Phone_number")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("tryout_gigamin1_nugi_mulya_nugraha.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Full_name")
                        .HasColumnType("text");

                    b.Property<string>("Phone_number")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("drivers");
                });

            modelBuilder.Entity("tryout_gigamin1_nugi_mulya_nugraha.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Cstmer_idId")
                        .HasColumnType("integer");

                    b.Property<int?>("Driver_idId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cstmer_idId");

                    b.HasIndex("Driver_idId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("tryout_gigamin1_nugi_mulya_nugraha.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("tryout_gigamin1_nugi_mulya_nugraha.Models.Order", b =>
                {
                    b.HasOne("tryout_gigamin1_nugi_mulya_nugraha.Models.Customer", "Cstmer_id")
                        .WithMany()
                        .HasForeignKey("Cstmer_idId");

                    b.HasOne("tryout_gigamin1_nugi_mulya_nugraha.Models.Driver", "Driver_id")
                        .WithMany()
                        .HasForeignKey("Driver_idId");
                });

            modelBuilder.Entity("tryout_gigamin1_nugi_mulya_nugraha.Models.Product", b =>
                {
                    b.HasOne("tryout_gigamin1_nugi_mulya_nugraha.Models.Order", null)
                        .WithMany("Order_detail")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
